name: enumerators
version: 0.4.3
author: Paul Brauner <polux@google.com>
description: A small DSL for writing enumerators of Dart datatypes, inspired by http://hackage.haskell.org/package/testing-feat
homepage: https://github.com/polux/enumerators
documentation: http://goo.gl/9AZBla
environment:
  sdk: '>=0.4.7'
dependencies:
  rational: '>=0.0.4 <1.0.0'
dev_dependencies:
  benchmark_harness: any
  unittest: any
